# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "backend.HeartbeatRequest" do
    optional :device_uid, :string, 1
    optional :timestamp, :int32, 2
  end
  add_message "backend.HeartbeatResponse" do
  end
end

module Backend
  HeartbeatRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("backend.HeartbeatRequest").msgclass
  HeartbeatResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("backend.HeartbeatResponse").msgclass
end
