# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "device.HeartbeatRequest" do
    optional :device_uid, :string, 1
    optional :timestamp, :int32, 2
  end
  add_message "device.HeartbeatResponse" do
  end
end

module Device
  HeartbeatRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("device.HeartbeatRequest").msgclass
  HeartbeatResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("device.HeartbeatResponse").msgclass
end
