default: &default
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: development

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3
